### ISSUE TITLE
Upgrade dependency to solve issues down the road

### ISSUE THREAD

**Issue by p-j** [Gaafar/deppie#2]
Hi @Gaafar 

We've been using deppie for a few month @vizeat but soon after setting it up, we realized [we had an issue](https://github.com/opbeat/opbeat-node/issues/104#issuecomment-273282324) with another tool.

Long story short, the issue is not with `deppie` per se, but with the dependency on an outdated version of [`madge`](https://github.com/pahen/madge) which itself depends on an outdated version of [`coffeescript`](https://github.com/jashkenas/coffeescript) which breaks the `Error.prepareStackTrace` by reassigning it to something different instead of wrapping it seamlessly, which breaks the monitoring/error reporting tool that we use : [opbeat](https://github.com/opbeat/opbeat-node/issues/104)

The maintainers of `coffeescript` have agreed that it was a mistake and removed this override in a recent version. But even closer to `deppie`, `madge`, since [`version 1.0`](https://github.com/pahen/madge/blob/master/CHANGELOG.md#v100-aug-19-2016) has dropped `coffeescript` support.

Do you intend to upgrade `madge` ?
I started having a look at it, but I'm a bit lost in what was the API provided by madge vs what is proposed now and what needs to be fixed.

I started working on it [here](https://github.com/vizeat/deppie/tree/chore/dependencies) but I'd be grateful if you had insights as to what needs to be fixed.

Thanks

**Comment by Gaafar** [comment]
I can't upgrade to madge v1 or higher as it broke the API and now uses an async promise, which I can't use as all my code is synchronous. I can however update to v0.6.0 (it passed my tests) but I'm not sure if that will solve your issue or not. You can check the source code here and see https://github.com/pahen/madge/tree/0.6.0

**Comment by p-j** [comment]
Unfortunately it still depends on [`coffeescript@1.10.0`](https://github.com/jashkenas/coffeescript) they fixed it in `1.12.1`

**Comment by p-j** [comment]
besides the async from `madge` what else would require fixing you think ?

**Comment by Gaafar** [comment]
Async is a deal breaker for me as I want deppie to work completely sync, there is nothing that needs to be async and it will add unneeded complexity and break the API. 

However, if you really need to, you can fork it. I am only using madge to check for circular dependencies and check if a module depends on a module that has no return (void module), these 2 functions are `checkCircularDependencies` and `checkVoidModules` respectively in `lib/checks.js`. You will need to rewrite these. But the problem is that making them async means you will have to change the whole flow of the code. Other than that, you can find another library that does the same checks sync or write that code yourself.

I intend to remove madge anyway and write these checks only, but it's not my top priority right now.

**Comment by p-j** [comment]
Understood, I started working on this yesterday, and in the mean time found a quick'n'dirty fix for our issue I mentioned earlier. I might go ahead with it later on to get a proper fix.

**Comment by p-j** [comment]
Since the issue is not with `deppie` per se, I'm going to close this.
Thanks for your help :+1:

**Comment by Gaafar** [comment]
no problem, good luck!
